name: cc_frontend
description: "CourierCompass"

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/svg/logo.svg
    - assets/svg/truck.svg
    - assets/svg/ship.svg
    - assets/svg/navi.svg